### ISSUE TITLE
这本书不更新了吗？

### ISSUE THREAD

**Issue by mazl** [TNK-Studio/Odoo-Book#25]
这本书不更新了吗？

**Comment by ruter** [comment]
作者本人（@elfgzp )忙于工作暂时没有精力持续更新，后续如果有更新我们会第一时间通知到你，感谢你的关注😉

**Comment by mazl** [comment]
好的，现在odoo的资源实在是太少了

**Comment by ruter** [comment]
如果需要的话，你这边可以加微信群，群里能及时提问 :)

请添加这个微信号，留言 Odoo，等待我们邀请入群

![Odoo WeChat Group](https://user-images.githubusercontent.com/8568876/64122513-6d2df500-cdd4-11e9-806c-9a73aa72b056.png)

**Comment by elfgzp** [comment]
更更更马上更
